### ISSUE TITLE
Error generating service

### ISSUE THREAD

**Issue by iztokb** [nestjs/nest-cli#124]
I get this error when executing command nest g service applicationSettings or nest generate service applicationSettings.

I'm using
Node v.8.11.1
npm 6.0.1
@nestjs/cli 5.1.2

```console
Cannot read property 'subfiles' of null
🙀  Failed to execute command: /home/iztok/.nvm/versions/node/v8.11.1/lib/node_modules/@nestjs/cli/node_modules/.bin/schematics @nestjs/schematics:service --name=application-settings --dry-run=false
(node:20962) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of undefined
    at Object.<anonymous> (/home/iztok/.nvm/versions/node/v8.11.1/lib/node_modules/@nestjs/cli/actions/generate.action.js:30:49)
    at Generator.throw (<anonymous>)
    at rejected (/home/iztok/.nvm/versions/node/v8.11.1/lib/node_modules/@nestjs/cli/actions/generate.action.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:20962) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20962) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ThomRick** [comment]
Hey @iztokb 

Are you in your project folder when executing this command ?

**Comment by ThomRick** [comment]
Ok cool ! Maybe we should increase the generate system with workspace definition like Angular-CLI do.
It will be in the next features ;-)

So stay in your project root folder to use Nest-CLI for the current versions ;-)
