### ISSUE TITLE
Cant use cli commands for generate code (module, controller, etc)

### ISSUE THREAD

**Issue by rseasta** [nestjs/nest-cli#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I use cli commands `nest g mo <name>` or `nest g controller <name>` or `nest g <other>` I get this error:
```
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/codegen/index.js:568:18)

Failed to execute command: node @nestjs/schematics:pipe --name=co --no-dry-run --language="ts" --sourceRoot="src" --spec
```
But `nest new <project>` work good
P.S. if I remove project node_modules dir and run `nest g <other>` it works good and then run `npm i` and `nest g <other>` get errors again

### Minimum reproduction code

no link

### Steps to reproduce

1. `nest new <project>`
2. `nest g module <module>`

### Expected behavior

You get this error:
```
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/user/Projects/microservice/tor/node_modules/ajv/dist/compile/codegen/index.js:568:18)

Failed to execute command: node @nestjs/schematics:pipe --name=co --no-dry-run --language="ts" --sourceRoot="src" --spec
```

### Package version

8.1.5

### NestJS version

8.1.4

### Node.js version

v16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I didn't manage to reproduce this in my Linux :/ everything went fine.

**Comment by kamilmysliwiec** [comment]
> P.S. if I remove project node_modules dir and run nest g <other> it works good and then run npm i and nest g <other> get errors again

Likely, your lock file contains an older version of the `@nestjs/schematics` package.
