### ISSUE TITLE
can not generate resource nestjs : typeScript

### ISSUE THREAD

**Issue by AshramC** [nestjs/nest-cli#1619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am getting this error when:
`nest g co moudle/abc --dry-run
`

```

TypeError: Cannot read properties of undefined (reading 'properties')
    at MetadataManager.insert (/Users/ashramc/Work/GMTool/hello-world/node_modules/@nestjs/schematics/dist/utils/metadata.manager.js:13:41)
    at ModuleMetadataDeclarator.declare (/Users/ashramc/Work/GMTool/hello-world/node_modules/@nestjs/schematics/dist/utils/module-metadata.declarator.js:8:34)
    at ModuleDeclarator.declare (/Users/ashramc/Work/GMTool/hello-world/node_modules/@nestjs/schematics/dist/utils/module.declarator.js:15:33)
    at /Users/ashramc/Work/GMTool/hello-world/node_modules/@nestjs/schematics/dist/lib/controller/controller.factory.js:60:51
    at MergeMapSubscriber.project (/Users/ashramc/Work/GMTool/hello-world/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/Users/ashramc/Work/GMTool/hello-world/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/Users/ashramc/Work/GMTool/hello-world/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at Subscriber.next (/Users/ashramc/Work/GMTool/hello-world/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/ashramc/Work/GMTool/hello-world/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/Users/ashramc/Work/GMTool/hello-world/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/innerSubscribe.js:27:21)

Failed to execute command: node @nestjs/schematics:controller --name=moudle/abc --dry-run --no-skipImport --language="ts" --sourceRoot="src" --spec

```

What I’ve tried so far:

```
nest update -f -t latest 
npm i -g @nestjs/schematics    

```

but they also did not work
Issue when creating new resources with nest g resource (controller,server,etc..)

**package.json**
```

{
  "name": "hello-world",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^8.4.4",
    "@nestjs/core": "^8.4.4",
    "@nestjs/platform-express": "^8.4.4",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.10",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.4.1",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}


```

### Minimum reproduction code

https://github.com/AshramC/HelloWorldNestJs

### Steps to reproduce

nest g co moudle/abc

### Expected behavior

no error

### Package version

8.0.0

### NestJS version

8.4.4

### Node.js version

18.0.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
what about `npx nest g co moudle/abc`

**Comment by AshramC** [comment]
> what about `npx nest g co moudle/abc`

same error
