### ISSUE TITLE
Could not generate module with nest cli

### ISSUE THREAD

**Issue by zaborius** [nestjs/nest-cli#1639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

command `nest g module-name` gives error:

> TypeError: Cannot read properties of null (reading '0')
    at MetadataManager.insertSymbolToMetadata (/Users/zaborius/projects/gift-app/server/node_modules/@nestjs/schematics/dist/utils/metadata.manager.js:131:60)
    at MetadataManager.insert (/Users/zaborius/projects/gift-app/server/node_modules/@nestjs/schematics/dist/utils/metadata.manager.js:42:25)
    at ModuleMetadataDeclarator.declare (/Users/zaborius/projects/gift-app/server/node_modules/@nestjs/schematics/dist/utils/module-metadata.declarator.js:8:34)
    at ModuleDeclarator.declare (/Users/zaborius/projects/gift-app/server/node_modules/@nestjs/schematics/dist/utils/module.declarator.js:15:33)
    at /Users/zaborius/projects/gift-app/server/node_modules/@nestjs/schematics/dist/lib/module/module.factory.js:55:51
    at MergeMapSubscriber.project (/Users/zaborius/projects/gift-app/server/node_modules/@nestjs/schematics/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/Users/zaborius/projects/gift-app/server/node_modules/@nestjs/schematics/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/Users/zaborius/projects/gift-app/server/node_modules/@nestjs/schematics/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/Users/zaborius/projects/gift-app/server/node_modules/@nestjs/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/zaborius/projects/gift-app/server/node_modules/@nestjs/schematics/node_modules/rxjs/internal/operators/mergeMap.js:93:26)

>Failed to execute command: node @nestjs/schematics:module --name=user-occasions --dry-run --no-skipImport --language="ts" --sourceRoot="src" --no-spec

### Minimum reproduction code

https://github.com/zaborius/nest-cli-bug-report

### Steps to reproduce

1. `nest new project-name` 
2. `cd project-name`
3. `nest g module hello`
4. open **app.module.ts**
5. remove indentation before **HelloModule** in **import** block on **line 8**
<img width="330" alt="image" src="https://user-images.githubusercontent.com/6203348/168456905-3751e23b-763a-41ae-9209-e569258b68d1.png">
6. nest g module goodbye

### Expected behavior

command `nest g module goodbye` creates new module

### Package version

8.2.4

### NestJS version

8.4.5

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Related issue #230

**Comment by Tony133** [comment]
I did some tests and at the moment I found that if the code is not set with the right indentation it generates the error (see screenshot)

<img width="1072" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/168479510-3e2a5483-000e-4b65-b02f-58cb9e5b6f4e.png">

<img width="1130" alt="screenshot2" src="https://user-images.githubusercontent.com/11542387/168479199-b5f2e4ec-5815-40a6-a502-8e05fd16b815.png">

**Comment by micalevisk** [comment]
that happen due to the following lines

https://github.com/nestjs/schematics/blob/51304108c170fdd66d5cef1836e0531bd8973e89/src/utils/metadata.manager.ts#L191-L196

because `text.match(/^\r?\n(\r?)\s+/)` returns `null`
