### ISSUE TITLE
@nestjs/cli build breaks 9.0 -> 9.1

### ISSUE THREAD

**Issue by horrendo** [nestjs/nest-cli#1778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Something seems to have changed (for the worst for us) with `nest build` going from 9.0 to 9.1.

With 9.0 everything is ok:

```
[~/git/unsullied] yarn list --pattern nestjs
yarn list v1.22.19
├─ @nestjs-plus/discovery@2.0.2
├─ @nestjs/cli@9.0.0
├─ @nestjs/common@9.0.11
├─ @nestjs/core@9.0.11
├─ @nestjs/platform-express@9.0.11
├─ @nestjs/schematics@9.0.3
└─ @nestjs/testing@9.0.11
✨  Done in 0.78s.
[~/git/unsullied] yarn nest build
yarn run v1.22.19
$ /Users/stbaldwin/git/unsullied/node_modules/.bin/nest build
✨  Done in 25.66s.
[~/git/unsullied] node -r tsconfig-paths/register dist/main.js
[Nest] 24328  - 07/09/2022, 12:41:28 am     LOG [main] Running unsullied app on Node.js v16.17.0.
[Nest] 24328  - 07/09/2022, 12:41:28 am     LOG [MasterHost] sqlite database found
[Nest] 24328  - 07/09/2022, 12:41:28 am     LOG [MasterHost] Opening database ./master-host.db
[Nest] 24328  - 07/09/2022, 12:41:28 am     LOG [NestFactory] Starting Nest application... +47ms
[Nest] 24328  - 07/09/2022, 12:41:29 am     LOG [InstanceLoader] TemplateModule dependencies initialized +186ms
:
```

Upgrading to 9.1+ breaks for us:

```
[~/git/unsullied] yarn upgrade @nestjs/cli@9.1.0
yarn upgrade v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning Workspaces can only be enabled in private projects.
[5/5] 🔨  Rebuilding all packages...
success Saved lockfile.
warning Workspaces can only be enabled in private projects.
success Saved 5 new dependencies.
info Direct dependencies
└─ @nestjs/cli@9.1.0
info All dependencies
├─ @angular-devkit/schematics-cli@14.2.0
├─ @nestjs/cli@9.1.0
├─ ansi-colors@4.1.3
├─ node-abort-controller@3.0.1
└─ tsconfig-paths-webpack-plugin@4.0.0
✨  Done in 12.81s.
[~/git/unsullied] yarn list --pattern nestjs
yarn list v1.22.19
├─ @nestjs-plus/discovery@2.0.2
├─ @nestjs/cli@9.1.0
├─ @nestjs/common@9.0.11
├─ @nestjs/core@9.0.11
├─ @nestjs/platform-express@9.0.11
├─ @nestjs/schematics@9.0.3
└─ @nestjs/testing@9.0.11
✨  Done in 0.77s.
[~/git/unsullied] yarn nest build
yarn run v1.22.19
$ /Users/stbaldwin/git/unsullied/node_modules/.bin/nest build
✨  Done in 25.85s.
[~/git/unsullied] node -r tsconfig-paths/register dist/main.js
[Nest] 25790  - 07/09/2022, 12:43:54 am     LOG [main] Running unsullied app on Node.js v16.17.0.
[Nest] 25790  - 07/09/2022, 12:43:54 am     LOG [MasterHost] sqlite database found
[Nest] 25790  - 07/09/2022, 12:43:54 am     LOG [MasterHost] Opening database ./master-host.db
[Nest] 25790  - 07/09/2022, 12:43:54 am     LOG [NestFactory] Starting Nest application... +43ms
[Nest] 25790  - 07/09/2022, 12:43:54 am     LOG [InjectorLogger] Nest encountered an undefined dependency. This may be due to a circular import or a missing dependency declaration.
[Nest] 25790  - 07/09/2022, 12:43:54 am   ERROR [ExceptionHandler] Nest can't resolve dependencies of the RepositoryCacheManager (?, NotificationListener, AppEventEmitter). Please make sure that the argument dependency at index [0] is available in the CacheModule context.

Potential solutions:
- If dependency is a provider, is it part of the current CacheModule?
- If dependency is exported from a separate @Module, is that module imported within CacheModule?
  @Module({
    imports: [ /* the Module containing dependency */ ]
  })

Error: Nest can't resolve dependencies of the RepositoryCacheManager (?, NotificationListener, AppEventEmitter). Please make sure that the argument dependency at index [0] is available in the CacheModule context.

Potential solutions:
- If dependency is a provider, is it part of the current CacheModule?
- If dependency is exported from a separate @Module, is that module imported within CacheModule?
  @Module({
    imports: [ /* the Module containing dependency */ ]
  })

    at Injector.resolveSingleParam (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:178:19)
    at resolveParam (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:116:49)
    at Array.map (<anonymous>)
    at Injector.resolveConstructorParams (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:131:58)
    at Injector.loadInstance (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:57:24)
    at Injector.loadProvider (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/injector.js:84:20)
    at /Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/instance-loader.js:47:62
    at Array.map (<anonymous>)
    at InstanceLoader.createInstancesOfProviders (/Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/instance-loader.js:47:36)
    at /Users/stbaldwin/git/unsullied/node_modules/@nestjs/core/injector/instance-loader.js:32:24
```

We can fix our max version of `@nestjs/cli` for now, but it would be good to know if this is a bug, or something we need to fix.

The dependency it is complaining about it provided in a `@Global()` module.

### Minimum reproduction code

See above

### Expected behavior

I would expect the build to generate runnable code as it did pre-9.1.0

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/cli

### NestJS version

9.0.11

### Packages versions

See above

### Node.js version

16.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by horrendo** [comment]
Sorry @jmcdo29 but for now I don't have time to build a minimum reproducible test case. Like I said, we can restrict the max version of `@nestjs/cli` in our package.json, so we have a clunky workaround. I guess this was more of a 'heads up' in case it affects others folks.

**Comment by jmcdo29** [comment]
The only thing I can _guess_ is that you're using 9.1.0 which had a bug in it that was resolved in 9.1.2 where absolute paths weren't treated and re-written properly by the `build` command. Without a reproduction though, there's not really anything we _can_ do

**Comment by micalevisk** [comment]
does `yarn nest start` works as expected?

**Comment by horrendo** [comment]
I don't know if this is relevant, but looking at the generated javascript files, the only difference between those generated by 9.0 and 9.1 is that 9.1 has some extra `require` lines. Here is one example of a file whose generated javascript changed from 9.0 to 9.1:

Original typescript:

```typescript
import { Injectable, Logger } from '@nestjs/common';
import { EnqueuedResultInsert } from '@/models/EnqueuedResult';
import { EnqueuedToDo } from '@/models/EnqueuedToDo';
import { ServiceCloudBuyerSyncService } from '@/business/serviceCloud/ServiceCloudBuyerSyncService';
import { ServiceCloudService } from '@/infrastructure/coms/ServiceCloudService';
import { InjectServiceCloudService } from '@/infrastructure/coms/InjectServiceCloudService';
import { LocalStorage } from '@/infrastructure/caching/LocalStorage';
import { BuyerRepository } from '@/business/repository/BuyerRepository';
import { ProgramRepository } from '@/business/repository/ProgramRepository';
import { ContactToContactMapper } from '@/business/serviceCloud/mappers/ContactToContactMapper';
import { BuyerToAccountMapper } from '@/business/serviceCloud/mappers/BuyerToAccountMapper';
import { ConnectionPool } from '@/infrastructure/database/ConnectionPool';
@Injectable()
export class ServiceCloudEnqueuedService {
    private logger = new Logger(ServiceCloudEnqueuedService.name);

    public constructor(
        @InjectServiceCloudService() private readonly serviceCloud: ServiceCloudService,
        private readonly buyerToAccountMapper: BuyerToAccountMapper,
        private readonly contactToCloudContactMapper: ContactToContactMapper,
        private readonly buyerRepository: BuyerRepository,
        private readonly programRepository: ProgramRepository,
        private readonly localStorage: LocalStorage,
        private readonly connectionPool: ConnectionPool
    ) {}

    /**
     * syncBuyer - Calls the service to sync the buyer data to ServiceCloud
     * @param enqueued An enqueued row to process
     */
    public async syncBuyer(enqueued: EnqueuedToDo): Promise<EnqueuedResultInsert> {
        this.logger.log('Started ServiceCloudEnqueuedService::syncBuyer');

        let resultStatus = 200;
        let resultBody;
        let isOK = true;

        try {
            await new ServiceCloudBuyerSyncService(
                this.serviceCloud,
                this.buyerToAccountMapper,
                this.contactToCloudContactMapper,
                this.buyerRepository,
                this.programRepository,
                this.localStorage,
                this.connectionPool
            ).syncBuyer(enqueued.objectId!);
        } catch (e) {
            resultStatus = 500;
            resultBody = `error: ${e}`;
            isOK = false;
        }

        const result: EnqueuedResultInsert = {
            enqueuedId: enqueued.id,
            resultStatus: resultStatus,
            resultBody: resultBody,
            isOk: isOK
        };

        return result;
    }
}
```

The version 9.0 js is:

```javascript
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var __param = (this && this.__param) || function (paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
};
var ServiceCloudEnqueuedService_1;
Object.defineProperty(exports, "__esModule", { value: true });
exports.ServiceCloudEnqueuedService = void 0;
const common_1 = require("@nestjs/common");
const ServiceCloudBuyerSyncService_1 = require("./ServiceCloudBuyerSyncService");
const InjectServiceCloudService_1 = require("../../infrastructure/coms/InjectServiceCloudService");
const LocalStorage_1 = require("../../infrastructure/caching/LocalStorage");
const BuyerRepository_1 = require("../repository/BuyerRepository");
const ProgramRepository_1 = require("../repository/ProgramRepository");
const ContactToContactMapper_1 = require("./mappers/ContactToContactMapper");
const BuyerToAccountMapper_1 = require("./mappers/BuyerToAccountMapper");
const ConnectionPool_1 = require("../../infrastructure/database/ConnectionPool");
let ServiceCloudEnqueuedService = ServiceCloudEnqueuedService_1 = class ServiceCloudEnqueuedService {
    constructor(serviceCloud, buyerToAccountMapper, contactToCloudContactMapper, buyerRepository, programRepository, localStorage, connectionPool) {
        this.serviceCloud = serviceCloud;
        this.buyerToAccountMapper = buyerToAccountMapper;
        this.contactToCloudContactMapper = contactToCloudContactMapper;
        this.buyerRepository = buyerRepository;
        this.programRepository = programRepository;
        this.localStorage = localStorage;
        this.connectionPool = connectionPool;
        this.logger = new common_1.Logger(ServiceCloudEnqueuedService_1.name);
    }
    async syncBuyer(enqueued) {
        this.logger.log('Started ServiceCloudEnqueuedService::syncBuyer');
        let resultStatus = 200;
        let resultBody;
        let isOK = true;
        try {
            await new ServiceCloudBuyerSyncService_1.ServiceCloudBuyerSyncService(this.serviceCloud, this.buyerToAccountMapper, this.contactToCloudContactMapper, this.buyerRepository, this.programRepository, this.localStorage, this.connectionPool).syncBuyer(enqueued.objectId);
        }
        catch (e) {
            resultStatus = 500;
            resultBody = `error: ${e}`;
            isOK = false;
        }
        const result = {
            enqueuedId: enqueued.id,
            resultStatus: resultStatus,
            resultBody: resultBody,
            isOk: isOK
        };
        return result;
    }
};
ServiceCloudEnqueuedService = ServiceCloudEnqueuedService_1 = __decorate([
    common_1.Injectable(),
    __param(0, InjectServiceCloudService_1.InjectServiceCloudService()),
    __metadata("design:paramtypes", [Object, BuyerToAccountMapper_1.BuyerToAccountMapper,
        ContactToContactMapper_1.ContactToContactMapper,
        BuyerRepository_1.BuyerRepository,
        ProgramRepository_1.ProgramRepository,
        LocalStorage_1.LocalStorage,
        ConnectionPool_1.ConnectionPool])
], ServiceCloudEnqueuedService);
exports.ServiceCloudEnqueuedService = ServiceCloudEnqueuedService;
//# sourceMappingURL=ServiceCloudEnqueuedService.js.map
```
The version 9.1 js is:

```javascript
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var __param = (this && this.__param) || function (paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
};
var ServiceCloudEnqueuedService_1;
Object.defineProperty(exports, "__esModule", { value: true });
exports.ServiceCloudEnqueuedService = void 0;
const common_1 = require("@nestjs/common");
const EnqueuedResult_1 = require("../../models/EnqueuedResult");
const EnqueuedToDo_1 = require("../../models/EnqueuedToDo");
const ServiceCloudBuyerSyncService_1 = require("./ServiceCloudBuyerSyncService");
const ServiceCloudService_1 = require("../../infrastructure/coms/ServiceCloudService");
const InjectServiceCloudService_1 = require("../../infrastructure/coms/InjectServiceCloudService");
const LocalStorage_1 = require("../../infrastructure/caching/LocalStorage");
const BuyerRepository_1 = require("../repository/BuyerRepository");
const ProgramRepository_1 = require("../repository/ProgramRepository");
const ContactToContactMapper_1 = require("./mappers/ContactToContactMapper");
const BuyerToAccountMapper_1 = require("./mappers/BuyerToAccountMapper");
const ConnectionPool_1 = require("../../infrastructure/database/ConnectionPool");
let ServiceCloudEnqueuedService = ServiceCloudEnqueuedService_1 = class ServiceCloudEnqueuedService {
    constructor(serviceCloud, buyerToAccountMapper, contactToCloudContactMapper, buyerRepository, programRepository, localStorage, connectionPool) {
        this.serviceCloud = serviceCloud;
        this.buyerToAccountMapper = buyerToAccountMapper;
        this.contactToCloudContactMapper = contactToCloudContactMapper;
        this.buyerRepository = buyerRepository;
        this.programRepository = programRepository;
        this.localStorage = localStorage;
        this.connectionPool = connectionPool;
        this.logger = new common_1.Logger(ServiceCloudEnqueuedService_1.name);
    }
    async syncBuyer(enqueued) {
        this.logger.log('Started ServiceCloudEnqueuedService::syncBuyer');
        let resultStatus = 200;
        let resultBody;
        let isOK = true;
        try {
            await new ServiceCloudBuyerSyncService_1.ServiceCloudBuyerSyncService(this.serviceCloud, this.buyerToAccountMapper, this.contactToCloudContactMapper, this.buyerRepository, this.programRepository, this.localStorage, this.connectionPool).syncBuyer(enqueued.objectId);
        }
        catch (e) {
            resultStatus = 500;
            resultBody = `error: ${e}`;
            isOK = false;
        }
        const result = {
            enqueuedId: enqueued.id,
            resultStatus: resultStatus,
            resultBody: resultBody,
            isOk: isOK
        };
        return result;
    }
};
ServiceCloudEnqueuedService = ServiceCloudEnqueuedService_1 = __decorate([
    common_1.Injectable(),
    __param(0, InjectServiceCloudService_1.InjectServiceCloudService()),
    __metadata("design:paramtypes", [Object, BuyerToAccountMapper_1.BuyerToAccountMapper,
        ContactToContactMapper_1.ContactToContactMapper,
        BuyerRepository_1.BuyerRepository,
        ProgramRepository_1.ProgramRepository,
        LocalStorage_1.LocalStorage,
        ConnectionPool_1.ConnectionPool])
], ServiceCloudEnqueuedService);
exports.ServiceCloudEnqueuedService = ServiceCloudEnqueuedService;
//# sourceMappingURL=ServiceCloudEnqueuedService.js.map
```

The 9.0 -> 9.1 diff is:

```
20a21
> const Buyer_1 = require("../../models/Buyer");
25a27
> const ServiceCloudService_1 = require("../../infrastructure/coms/ServiceCloudService");
29a32
> const SchedulableOptions_1 = require("../../infrastructure/scheduler/SchedulableOptions");
```

**Comment by micalevisk** [comment]
show us your tsconfig as well

**Comment by horrendo** [comment]
```
[~/git/unsullied] cat tsconfig.json
{
    "compilerOptions": {
        "allowJs": false,
        "module": "commonjs",
        "declaration": true,
        "removeComments": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "strict": true,
        "suppressImplicitAnyIndexErrors": true,
        "target": "es2020",
        "lib": ["es2020"],
        "sourceMap": true,
        "outDir": "./dist",
        "baseUrl": "./",
        "paths": {
            "@/*": ["src/*"],
            "*": ["src/typings/*"]
        }
    },
    "exclude": ["node_modules", "aurora", "build", "dist", "dev-tools"]
}
[~/git/unsullied] cat tsconfig.build.json
{
    "extends": "./tsconfig.json",
    "exclude": ["node_modules", "test", "**/*spec.ts", "aurora", "dist", "dev-tools", "spec"]
}
```

**Comment by horrendo** [comment]
And `yarn nest start` exhibits identical behaviour. That is, it works with `@nestjs/cli 9.0.0` and fails with the above error with `@nestjs/cli 9.1.0`.

**Comment by jmcdo29** [comment]
Okay, this is probably another side effect of typescript 4.8 and the AST changes they made. I would bet if you use `import type { ServiceCloudService } from ...` instead of `import { ServiceCloudService } from ...` it would be fixed. 

For anything further we need a minimum reproduction.

**Comment by danewilson** [comment]
This looks the same issue I raised which does have a minimum repro: https://github.com/nestjs/nest-cli/issues/1772

**Comment by horrendo** [comment]
> This looks like the same issue I raised which does have a minimum repro: #1772

Agreed. Thanks - I'll close this one.
