### ISSUE TITLE
TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU

### ISSUE THREAD

**Issue by dschuessler** [nestjs/nest-cli#2086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
(default) MacBook-Pro:demo_app xxx$ npx @nestjs/cli new backend
⚡  We will scaffold your app in a few seconds..

? Which package manager would you ❤️  to use? yarn
node:internal/encoding:485
          throw new ERR_NO_ICU('"fatal" option');
          ^

TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU
    at new NodeError (node:internal/errors:399:5)
    at new TextDecoder (node:internal/encoding:485:17)
    at Object.<anonymous> (/Users/xxx/.npm/_npx/ccf722f030a36e55/node_modules/@angular-devkit/schematics/src/rules/template.js:33:17)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/xxx/.npm/_npx/ccf722f030a36e55/node_modules/@angular-devkit/schematics/src/index.js:56:14) {
  code: 'ERR_NO_ICU'
}

Node.js v18.15.0

Failed to execute command: node @nestjs/schematics:application --name=backend --directory=undefined --no-dry-run --no-skip-git --no-strict --package-manager="yarn" --collection="@nestjs/schematics" --language="ts"
```

### Minimum reproduction code

Since this happens with CLI usage, I don't see how I can provide meaningful reproduction code.

### Steps to reproduce

1. Install anaconda
2. `anaconda-project init -y --directory demo_app`
3. `cd demo_app`
4. `anaconda-project add-packages nodejs`
5. `conda activate envs/default`
6. `npx @nestjs/cli new backend`

### Expected behavior

```
(base) MacBook-Pro:~ xxx$ npx @nestjs/cli new backend
⚡  We will scaffold your app in a few seconds..

CREATE backend/.eslintrc.js (665 bytes)
CREATE backend/.prettierrc (51 bytes)
CREATE backend/README.md (3340 bytes)
CREATE backend/nest-cli.json (118 bytes)
CREATE backend/package.json (1992 bytes)
CREATE backend/tsconfig.build.json (97 bytes)
CREATE backend/tsconfig.json (546 bytes)
CREATE backend/src/app.controller.spec.ts (617 bytes)
CREATE backend/src/app.controller.ts (274 bytes)
CREATE backend/src/app.module.ts (249 bytes)
CREATE backend/src/app.service.ts (142 bytes)
CREATE backend/src/main.ts (208 bytes)
CREATE backend/test/app.e2e-spec.ts (630 bytes)
CREATE backend/test/jest-e2e.json (183 bytes)

? Which package manager would you ❤️  to use? npm
✔ Installation in progress... ☕

🚀  Successfully created project backend
👉  Get started with the following commands:

$ cd backend
$ npm run start

                                         
                          Thanks for installing Nest 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.
                                         
                                         
               🍷  Donate: https://opencollective.com/nest
                                        
```

### Package version

9.1.5

### NestJS version

9.5.0

### Node.js version

18.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Apparently, nest.js relies on node.js being built with ICU, which does not seem to be the case for the node.js binary distributed via conda. However, I could not find any mention of this requirement in the documentation.

If this is to be expected, I can open an MR for the documentation, if you're interested.

The behavior happens regardless of whether I use `npx` or do a global install beforehand.

**Comment by micalevisk** [comment]
I guess there's nothing to do other than documenting this requirement at https://docs.nestjs.com/cli/overview :/

**Comment by kamilmysliwiec** [comment]
This seems to be related to the `@angular-devkit/schematics` package so I'd suggest creating an issue there.

PR to the docs are more than welcome!
