### ISSUE TITLE
alias path not working for @nestjs/cli@9.5.0

### ISSUE THREAD

**Issue by zhouweiming** [nestjs/nest-cli#2111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

pnpm run start

aa@0.0.1 start ***
nest start

Error: Cannot find module '@/app.module'
Require stack:

/dist/main.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
at Function.Module._load (node:internal/modules/cjs/loader:934:27)
at Module.require (node:internal/modules/cjs/loader:1157:19)
at require (node:internal/modules/helpers:119:18)
at Object. (/src/main.ts:2:1)
at Module._compile (node:internal/modules/cjs/loader:1275:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
at Module.load (node:internal/modules/cjs/loader:1133:32)
at Function.Module._load (node:internal/modules/cjs/loader:972:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
 ELIFECYCLE  Command failed with exit code 1.

### Minimum reproduction code

https://github.com/zhouweiming/nestjs-demo.git

### Steps to reproduce

clone the minimum reproduction code: https://github.com/zhouweiming/nestjs-demo.git
cd
pnpm install
pnpm start

### Expected behavior

I only made two modifications: 1. Add paths to tsconfig.json; 2. Modify the import of app. module in main.ts
```
pnpm run start

> aa@0.0.1 start ***
> nest start

Error: Cannot find module '@/app.module'
Require stack:
- ***/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Function.Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (***/src/main.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Function.Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
```

### Package version

9.5.0

### NestJS version

9.0.0

### Node.js version

v19.7.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

```
nest info

| \ | | | | |_ |/ |/ __ | | | |
| | | ___ ___ | | | |\ --. | /  \/| |     | | | .  | / _ / __|| __| | | `--. | | | | | |
| |\ || /_ | | /_/ //_/ /| _/| |_____| |
_| _/ _||/ _|_/ _/ _/__/___/

[System Information]
OS Version : macOS Unknown
NodeJS Version : v19.7.0
PNPM Version : 8.6.0

[Nest CLI]
Nest CLI Version : 9.0.0

[Nest Platform Information]
platform-express version : 9.0.0
schematics version : 9.0.0
testing version : 9.0.0
common version : 9.0.0
core version : 9.0.0
cli version : 9.0.0
```

**Comment by micalevisk** [comment]
everything went fine here

![image](https://github.com/nestjs/nest-cli/assets/13461315/d8244225-114c-44e3-a2b2-a1b45a6d7f5e)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
