### ISSUE TITLE
Nest build does not import enum in compiled js file

### ISSUE THREAD

**Issue by brdar** [nestjs/nest-cli#2125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have this TypeORM class:
```
import { AutoMap } from '@automapper/classes';
import { Column } from 'typeorm';
import { CsvDelimiter } from 'src/common/enum/csv-delimiter';

export abstract class CatalogFields {
  @AutoMap()
  @Column('varchar', { name: 'id', nullable: false, length: 255 })
  id: string;

  @AutoMap()
  @Column('enum', {
    name: 'delimiter',
    nullable: false,
    //This is a HACK!, TypeORM has bug with detecting change in enum like ',',';'
    //Bug causes constant changes to delimeter column when creating new migration.
    //Correct property is:
    //enum: CsvDelimiter,
    enum: ["'", "'", ';', '|', '	'],
    default: CsvDelimiter.SEMICOLON,
  })
  delimiter: CsvDelimiter;
}
```

and this enum:
```
export enum CsvDelimiter {
  COMMA = ',',
  PIPE = '|',
  SEMICOLON = ';',
  TAB = '\t',
}
```

when compiled with the latest version of nestjs/cli we get an error on app start:
```
/app/dist/database/entity/catalog-fields.js:78
        default: csv_delimiter_1.CsvDelimiter.SEMICOLON,
                 ^
ReferenceError: csv_delimiter_1 is not defined
    at Object.<anonymous> (/app/dist/database/entity/catalog-fields.js:78:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/dist/database/entity/catalog-shop-system.js:15:26)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

I have pulled built file from docker container and compared it to a file that I locally built (it locally works on my side as I have older version of nest/cli) and there is a one line difference marked in code below. 

```
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CatalogFields = void 0;
const classes_1 = require("@automapper/classes");
const typeorm_1 = require("typeorm");
const boolean_transformer_1 = require("../utils/boolean.transformer");
const csv_delimiter_1 = require("../../common/enum/csv-delimiter"); // <---- THIS LINE IS MISSING IN 10.0.1
class CatalogFields {
}
__decorate([
    classes_1.AutoMap(),
    typeorm_1.Column('varchar', { name: 'id', nullable: false, length: 255 }),
    __metadata("design:type", String)
], CatalogFields.prototype, "id", void 0);
__decorate([
    classes_1.AutoMap(),
    typeorm_1.Column('enum', {
        name: 'delimiter',
        nullable: false,
        //This is a HACK!, TypeORM has bug with detecting change in enum like ',',';'
        //Bug causes constant changes to delimeter column when creating new migration.
        //Correct property is:
        //enum: CsvDelimiter,
        enum: ["'", "'", ';', '|', '	'],
        default: csv_delimiter_1.CsvDelimiter.SEMICOLON,
    }),
    __metadata("design:type", String)
], CatalogFields.prototype, "delimiter", void 0);

exports.CatalogFields = CatalogFields;
//# sourceMappingURL=catalog-fields.js.map
```

### Minimum reproduction code

added above

### Steps to reproduce

FROM node:16.15.0-alpine as build

RUN mkdir /app
WORKDIR /app
COPY package*.json ./
COPY tsconfig*.json ./
COPY src ./src
RUN npm install --quiet node-pre-gyp -g \
    && npm ci \
    && npm i -g @nestjs/cli
RUN nest build

### Expected behavior

This import should have been added:
``const csv_delimiter_1 = require("../../common/enum/csv-delimiter"); ``

### Package version

10.0.1

### NestJS version

7.6.17

### Node.js version

16.15.0-alpine

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

Also, you should never use absolute paths starting with `src` in your project. Once the application is compiled, there's no `src` folder anymore.
