### ISSUE TITLE
Generating into a module with ES6 "spread" operator used, throws error

### ISSUE THREAD

**Issue by visurel** [nestjs/nest-cli#37]
When generating a new component into a module that uses the ES6 "spread" operator (as mentioned in the official documentation when using "providers") an error is thrown and the files are not generated.

```bash
nest g component invoiceLine invoice
create src\app\modules\invoice\services\invoiceLine\invoiceLine.service.ts
create src\app\modules\invoice\services\invoiceLine\invoiceLine.service.spec.ts
undefined:6
    ..."invoiceProviders",
    ^

SyntaxError: Unexpected token . in JSON at position 70
    at JSON.parse (<anonymous>)
    at MetadataTransform._transform (C:\Users\...\scoop\persist\nodejs\bin\node_modules\@nestjs\cli\bin\core\assets\streams\metadata.transform.js:13:43)
    at MetadataTransform.Transform._read (_stream_transform.js:186:10)
    at MetadataTransform.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at MetadataTransform.Writable.write (_stream_writable.js:290:11)
    at ImportTransform.ondata (_stream_readable.js:640:20)
    at emitOne (events.js:115:13)
    at ImportTransform.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:247:13)
    at ImportTransform.Readable.push (_stream_readable.js:209:10)
    at ImportTransform.Transform.push (_stream_transform.js:147:32)
    at ImportTransform._transform (C:\Users\...\scoop\persist\nodejs\bin\node_modules\@nestjs\cli\bin\core\assets\streams\import.transform.js:13:14)
    at ImportTransform.Transform._read (_stream_transform.js:186:10)

```
```typescript
@Module({
  modules: [
    DatabaseModule
  ],
  components: [
    ...invoiceProviders,
    InvoiceService,
  ],
  exports: [
    ...invoiceProviders
  ]
})
export class InvoiceModule {
}
```

**Comment by gimox** [comment]
same error here!
