### ISSUE TITLE
[BUG] - Creating a new project with --dry-run

### ISSUE THREAD

**Issue by mayordwells** [nestjs/nest-cli#73]
I got the following while trying to create a new project. However, it worked fine without the --dry-run flag.

```
Workspace $ nest new crypto-blogger-sample-api --dry-run
? description : crypto news
? version : 1.0.0
? author : Mayowa
CREATE /crypto-blogger-sample-api/.prettierrc (51 bytes)
CREATE /crypto-blogger-sample-api/README.md (355 bytes)
CREATE /crypto-blogger-sample-api/nodemon.json (147 bytes)
CREATE /crypto-blogger-sample-api/package.json (1367 bytes)
CREATE /crypto-blogger-sample-api/src/app.controller.spec.ts (564 bytes)
CREATE /crypto-blogger-sample-api/src/app.controller.ts (155 bytes)
CREATE /crypto-blogger-sample-api/src/app.module.ts (211 bytes)
CREATE /crypto-blogger-sample-api/src/main.ts (222 bytes)
CREATE /crypto-blogger-sample-api/test/app.e2e-spec.ts (593 bytes)
CREATE /crypto-blogger-sample-api/test/jest-e2e.json (169 bytes)
CREATE /crypto-blogger-sample-api/tsconfig.json (477 bytes)
CREATE /crypto-blogger-sample-api/tslint.json (895 bytes)
? Which package manager to use ? npm
Installing packages for tooling via npm
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by ThomRick** [comment]
Fix done ! Please upgrade to 4.0.0-rc2
