### ISSUE TITLE
Errored To run after re generate project via @nestjs/cli@7.5.3

### ISSUE THREAD

**Issue by xswei** [nestjs/nest-cli#989]
## I'm submitting a...

Errored To run after re generate project

```
nest new start-nest
```

## Current behavior

```
(node:50112) UnhandledPromiseRejectionWarning: TypeError: shared_utils_1.addLeadingSlash is not a function
    at NestApplication.registerRouter (D:\start-nest-7\node_modules\@nestjs\core\nest-application.js:104:41)
    at async NestApplication.init (D:\start-nest-7\node_modules\@nestjs\core\nest-application.js:90:9)
    at async NestApplication.listen (D:\start-nest-7\node_modules\@nestjs\core\nest-application.js:145:33)
    at async bootstrap (D:\start-nest-7\dist\main.js:7:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:50112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or b
y rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (s
ee https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:50112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js pr
ocess with a non-zero exit code.
```

## Expected behavior

run successful

## Minimal reproduction of the problem with instructions

1. install latest @nestjs/cli

2. new a project

3. yarn start OR npm run start

## Environment

```

```

**Comment by YashKumarVerma** [comment]
@xswei thanks for reporting the issue. could you share the exact version of nest-cli?

**Comment by xswei** [comment]
@YashKumarVerma   

My version is  7.5.4 ;  below is my project package content: 

```json
{
  "name": "start-nest",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^7.5.1",
    "@nestjs/core": "^7.5.1",
    "@nestjs/platform-express": "^7.5.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.3"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.5.1",
    "@nestjs/schematics": "^7.1.3",
    "@nestjs/testing": "^7.5.1",
    "@types/express": "^4.17.8",
    "@types/jest": "^26.0.15",
    "@types/node": "^14.14.6",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.6.1",
    "@typescript-eslint/parser": "^4.6.1",
    "eslint": "^7.12.1",
    "eslint-config-prettier": "7.0.0",
    "eslint-plugin-prettier": "^3.1.4",
    "jest": "^26.6.3",
    "prettier": "^2.1.2",
    "supertest": "^6.0.0",
    "ts-jest": "^26.4.3",
    "ts-loader": "^8.0.8",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.0.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

**Comment by xswei** [comment]
@YashKumarVerma  

It's running successful after i lock the `@nestjs/core` version to `7.5.5`

**Comment by YashKumarVerma** [comment]
@xswei i tried reproducing the issue, here are the steps I followed:

- `npm init -y`
- `npm i @nestjs/cli --> installs latest`
- `./node_modules/@nestjs/cli/bin/nest.js --version`
> 7.5.4
- `./node_modules/@nestjs/cli/bin/nest.js new start-nest`
- `cd start-nest`
- `npm run start`

and the application successfully runs. Could you please help by telling me which step should I alter?

**Comment by xswei** [comment]
@YashKumarVerma 

I tried by your steps, running successed;  

**BUT** it's failed when I choose `yarn`

**Comment by YashKumarVerma** [comment]
@xswei I spun up a new docker container with `ubuntu:latest`, installed yarn, and ran the above commands to ensure that there was nothing else interfering with the installation.

![image](https://user-images.githubusercontent.com/14032427/101862281-00d5a000-3b98-11eb-9597-1fd71d411032.png)
![image](https://user-images.githubusercontent.com/14032427/101862286-03d09080-3b98-11eb-9e9a-12c01a26b920.png)


The package ran, without errors.

**Comment by xswei** [comment]
@YashKumarVerma 

Thank you bro;
So it seems that is my problem; I will check it again~~

**Comment by xswei** [comment]
@YashKumarVerma 

I got the reason,  it's interesting that when i switch to npm offical registry, everything runs ok; but failed when use my company private registry~

I don't want to go deeper~ worked ok is enough.

**Comment by YashKumarVerma** [comment]
Glad to know that this was resolved. Should we close this issue then ?

**Comment by xswei** [comment]
> Glad to know that this was resolved. Should we close this issue then ?

I closed it
